---
title: "Acomodar datos personales"
author: "Elizabeth Cattaneo"
date: "9/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**OBJETIVO**

Juntar en una variable el Apellido y el Nombre de cada estudiante para las comisiones MM y VM. Esto no es tidy pero los demás JTPs de la cátedra tienen sus alumnos organizados así.

Para pasar notas y demás chequeos tengo como id el número de legajo

Parto de las listas ordenadas por número de legajo que usamos para tomar el parcial de julio.

```{r}
# importo librerias
library(readxl)
library(dplyr)
library(tidyr)
```

```{r}
# importo datos 
martes <- read_xlsx("parcial_martes2022.xlsx", col_names = T)
viernes <- read_xlsx("parcial_viernes2022.xlsx", col_names = T)
```

```{r}
# creo nueva variable combinando Apellido y Nombre
martes <- martes %>% 
  unite("Apellido y Nombre", Apellido:Nombre, sep = ", ")

viernes <- viernes %>% 
  unite("Apellido y Nombre", Apellido:Nombre, sep = ", ")
```

```{r}
write.table(martes, "parcial2_martes2022.xlsx", sep = ",", col.names = T, row.names = F)

write.table(viernes, "parcial2_viernes2022.xlsx", sep = ",", col.names = T, row.names = F)
```


